//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conexiones
    {
        public Conexiones()
        {
            this.Vuelo = new HashSet<Vuelo>();
        }
    
        public string AerolineaID { get; set; }
        public int ConexionID { get; set; }
        public string CiudadOrigen { get; set; }
        public string PaisOrigen { get; set; }
        public string CiudadDestino { get; set; }
        public string PaisDestino { get; set; }
        public System.TimeSpan HorarioSalida { get; set; }
        public System.TimeSpan HorarioLlegada { get; set; }

        public string Info
        {
            get
            {
                return "Salida: " + CiudadOrigen + " " + HorarioSalida + " - Llegada: " + CiudadDestino + " " + HorarioLlegada;
            }
        }

        public virtual Aerolineas Aerolineas { get; set; }
        public virtual ICollection<Vuelo> Vuelo { get; set; }
    }
}
