//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaVuelosEntities : DbContext
    {
        public SistemaVuelosEntities()
            : base("name=SistemaVuelosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aerolineas> Aerolineas { get; set; }
        public DbSet<Boleto> Boleto { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Conexiones> Conexiones { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Encargado> Encargado { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Vuelo> Vuelo { get; set; }
    }
}
