//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        public Vuelo()
        {
            this.Boleto = new HashSet<Boleto>();
        }
    
        public string AerolineaID { get; set; }
        public int ConexionID { get; set; }
        public System.DateTime fecha { get; set; }
        public int idVuelo { get; set; }
        public int cantAsientos { get; set; }
        public int cantOcupados { get; set; }
    
        public virtual ICollection<Boleto> Boleto { get; set; }
        public virtual Conexiones Conexiones { get; set; }
    }
}
