//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class RecetasEntities : DbContext
{
    public RecetasEntities()
        : base("name=RecetasEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Ingrediente> Ingrediente { get; set; }
    public DbSet<Receta> Receta { get; set; }
    public DbSet<RecetaIngrediente> RecetaIngrediente { get; set; }
}
