//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionamientoMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstacionamientoEntities : DbContext
    {
        public EstacionamientoEntities()
            : base("name=EstacionamientoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Parcela> Parcela { get; set; }
        public DbSet<Registros> Registros { get; set; }
        public DbSet<TipoDeVehiculo> TipoDeVehiculo { get; set; }
        public DbSet<Vehiculo> Vehiculo { get; set; }
    }
}
