//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class LibroDBEntities : DbContext
{
    public LibroDBEntities()
        : base("name=LibroDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Autor> Autor { get; set; }
    public DbSet<Editorial> Editorial { get; set; }
    public DbSet<Genero> Genero { get; set; }
    public DbSet<Libro> Libro { get; set; }
}
